### ISSUE TITLE
Convert a User's Public Wikis to Private when Account Downgraded

### ISSUE THREAD

**Issue by austin-thesing** [austin-thesing/blocpedia#9]
@cbeck I tried several ways of doing this and I think I over complicated them....

**Comment by cbeck** [comment]
Ummm, not sure why you assigned a new issue to me about this. Did you mean to create a pull request?

**Comment by austin-thesing** [comment]
Oops sorry. I got the user downgrade method working.. But for some reason I can't seem to figure out how to turn the wikis all public.

**Comment by cbeck** [comment]
current_user.wikis.update_all(private: false)

**Comment by austin-thesing** [comment]
I tried that and for some reason it kicks back an error `undefined method "wikis" for #<User:0x007f8ec7e65a98>` which is the current user object

**Comment by cbeck** [comment]
make sure user has_many :wikis in the model

**Comment by cbeck** [comment]
looks to me like it doesn't

**Comment by austin-thesing** [comment]
Well that was incredibly easy.... Hahaha 😬😂. 
How did I miss that... I wonder if it got deleted in a prior checkpoint on accident

**Comment by cbeck** [comment]
you had to add that by hand, so if you didn't remember to do it after you created your wikis model, it was never done. It would have added belongs_to :user in the wiki model though
